### ISSUE TITLE
Aggressive ModelResolutionException while opening and using NetBeans

### ISSUE THREAD

**Issue by Chris2011** [ceylon/ceylon-ide-netbeans#4]
I thought this exception only comes, while opening NetBeans, but this comes often while working with NetBeans and opening a new Project or searching:

```
com.redhat.ceylon.model.loader.ModelResolutionException: Failed to resolve ceylon.language.empty_
	at com.redhat.ceylon.model.loader.AbstractModelLoader$7.call(AbstractModelLoader.java:2015)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$7.call(AbstractModelLoader.java:1910)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:415)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.embeddingSync(AbstractModelLoader.java:406)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:411)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1910)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1905)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.getDeclaration(AbstractModelLoader.java:5955)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toProducedType(TypeDescriptor.java:318)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toType(TypeDescriptor.java:310)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getProducedType(Metamodel.java:361)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.is(TypeDescriptor.java:1516)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.is(TypeDescriptor.java:270)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.isReified(Metamodel.java:326)
	at com.redhat.ceylon.compiler.java.Util.isReified(Util.java:79)
	at ceylon.language.Iterable$impl.sequence(Iterable.ceylon:289)
	at ceylon.language.Map$impl$Items.sequence(Map.ceylon)
	at com.redhat.ceylon.ide.common.model.CeylonProjects$3.$call$(CeylonProjects.ceylon:110)
	at com.redhat.ceylon.ide.common.model.CeylonProjects.withLocking$priv$(CeylonProjects.ceylon:89)
	at com.redhat.ceylon.ide.common.model.CeylonProjects.getCeylonProjects(CeylonProjects.ceylon:108)
	at com.redhat.ceylon.ide.common.model.CeylonProjects.fileTreeChanged(CeylonProjects.ceylon:195)
	at com.redhat.ceylon.ide.netbeans.model.CeylonModelManager.notifyChanges$priv$(CeylonModelManager.ceylon:120)
	at com.redhat.ceylon.ide.netbeans.model.CeylonModelManager.fileChanged(CeylonModelManager.ceylon:137)
[catch] at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEventImpl(FCLSupport.java:178)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapperMulti.dispatchAllEventsSync(FCLSupport.java:248)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEvent(FCLSupport.java:137)
	at org.openide.filesystems.FCLSupport.dispatchEvent(FCLSupport.java:112)
	at org.openide.filesystems.FileObject$ED.dispatch(FileObject.java:1435)
	at org.openide.filesystems.EventControl.invokeDispatchers(EventControl.java:213)
	at org.openide.filesystems.EventControl.exitAtomicAction(EventControl.java:188)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:129)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:519)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:421)
	at org.openide.text.DataEditorSupport.saveDocument(DataEditorSupport.java:603)
	at org.openide.loaders.DefaultES$SaveCookieImpl.save(DefaultES.java:207)
	at org.openide.actions.SaveAction.performAction(SaveAction.java:132)
	at org.openide.actions.SaveAction.performAction(SaveAction.java:102)
	at org.openide.actions.SaveAction$Delegate.actionPerformed(SaveAction.java:249)
	at org.openide.awt.ContextAction$Performer.actionPerformed(ContextAction.java:231)
	at org.openide.awt.ContextManager.actionPerformed(ContextManager.java:260)
	at org.openide.awt.ContextAction.actionPerformed(ContextAction.java:109)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:93)
	at org.openide.util.actions.ActionInvoker$ActionRunnable.actionPerformed(ActionInvoker.java:162)
	at org.netbeans.core.ModuleActions.invokeAction(ModuleActions.java:109)
	at org.netbeans.modules.openide.actions.ActionsBridgeImpl.invokeAction(ActionsBridgeImpl.java:60)
	at org.openide.util.actions.ActionInvoker$ActionRunnable.doRun(ActionInvoker.java:153)
	at org.openide.util.actions.ActionInvoker$2.run(ActionInvoker.java:110)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
```

I think this has a lot of other wrong behaviours.

Regards

Chris

**Comment by bjansen** [comment]
I believe it should be fixed, there was a hardcoded path in the code that pointed to a directory that only exists on my machine :)

**Comment by Chris2011** [comment]
Unfortunately not :(

```
com.redhat.ceylon.model.loader.ModelResolutionException: Failed to resolve ceylon.language.empty_
	at com.redhat.ceylon.model.loader.AbstractModelLoader$7.call(AbstractModelLoader.java:2015)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$7.call(AbstractModelLoader.java:1910)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:415)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.embeddingSync(AbstractModelLoader.java:406)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:411)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1910)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1905)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.getDeclaration(AbstractModelLoader.java:5955)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toProducedType(TypeDescriptor.java:318)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toType(TypeDescriptor.java:310)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getProducedType(Metamodel.java:361)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.is(TypeDescriptor.java:1516)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.is(TypeDescriptor.java:270)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.isReified(Metamodel.java:326)
	at com.redhat.ceylon.compiler.java.Util.isReified(Util.java:79)
	at ceylon.language.Iterable$impl.sequence(Iterable.ceylon:289)
	at ceylon.language.Map$impl$Items.sequence(Map.ceylon)
	at com.redhat.ceylon.ide.common.model.CeylonProjects$3.$call$(CeylonProjects.ceylon:110)
	at com.redhat.ceylon.ide.common.model.CeylonProjects.withLocking$priv$(CeylonProjects.ceylon:89)
	at com.redhat.ceylon.ide.common.model.CeylonProjects.getCeylonProjects(CeylonProjects.ceylon:108)
	at com.redhat.ceylon.ide.common.model.CeylonProjects.fileTreeChanged(CeylonProjects.ceylon:195)
	at com.redhat.ceylon.ide.netbeans.model.CeylonModelManager.notifyChanges$priv$(CeylonModelManager.ceylon:120)
	at com.redhat.ceylon.ide.netbeans.model.CeylonModelManager.fileChanged(CeylonModelManager.ceylon:137)
[catch] at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEventImpl(FCLSupport.java:178)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapperMulti.dispatchAllEventsSync(FCLSupport.java:248)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEvent(FCLSupport.java:137)
	at org.openide.filesystems.FCLSupport.dispatchEvent(FCLSupport.java:112)
	at org.openide.filesystems.FileObject$ED.dispatch(FileObject.java:1435)
	at org.openide.filesystems.FileSystem$EventDispatcher.run(FileSystem.java:795)
	at org.openide.filesystems.EventControl.dispatchEvent(EventControl.java:84)
	at org.openide.filesystems.FileSystem.dispatchEvent(FileSystem.java:554)
	at org.openide.filesystems.FileObject.dispatchEvent(FileObject.java:644)
	at org.openide.filesystems.FileObject.fireFileChangedEvent(FileObject.java:612)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj.fireFileChangedEvent(BaseFileObj.java:717)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObj$1.close(FileObj.java:156)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
	at org.openide.filesystems.FileObject$1.close(FileObject.java:829)
	at org.netbeans.modules.parsing.impl.indexing.IndexerCache.writeLastKnownIndexers(IndexerCache.java:681)
	at org.netbeans.modules.parsing.impl.indexing.IndexerCache.getData(IndexerCache.java:491)
	at org.netbeans.modules.parsing.impl.indexing.IndexerCache.getIndexers(IndexerCache.java:127)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$SourceIndexers.<init>(RepositoryUpdater.java:6484)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$SourceIndexers.load(RepositoryUpdater.java:6467)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.getSourceIndexers(RepositoryUpdater.java:2242)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$InitialRootsWork.getDone(RepositoryUpdater.java:5835)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doTheWork(RepositoryUpdater.java:3435)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task._run(RepositoryUpdater.java:6198)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.access$4300(RepositoryUpdater.java:5849)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2$1.run(RepositoryUpdater.java:6114)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:304)
	at org.netbeans.modules.parsing.impl.RunWhenScanFinishedSupport.performScan(RunWhenScanFinishedSupport.java:106)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6110)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6106)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:176)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:360)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:141)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:88)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.run(RepositoryUpdater.java:6106)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
SEVERE [org.openide.util.Exceptions]
com.redhat.ceylon.model.loader.ModelResolutionException: Failed to resolve ceylon.language.empty_
	at com.redhat.ceylon.model.loader.AbstractModelLoader$7.call(AbstractModelLoader.java:2015)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$7.call(AbstractModelLoader.java:1910)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:415)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.embeddingSync(AbstractModelLoader.java:406)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:411)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1910)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1905)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.getDeclaration(AbstractModelLoader.java:5955)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toProducedType(TypeDescriptor.java:318)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toType(TypeDescriptor.java:310)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getProducedType(Metamodel.java:361)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.is(TypeDescriptor.java:1516)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.is(TypeDescriptor.java:270)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.isReified(Metamodel.java:326)
	at com.redhat.ceylon.compiler.java.Util.isReified(Util.java:79)
	at ceylon.language.Iterable$impl.sequence(Iterable.ceylon:289)
	at ceylon.language.Map$impl$Items.sequence(Map.ceylon)
	at com.redhat.ceylon.ide.common.model.CeylonProjects$3.$call$(CeylonProjects.ceylon:110)
	at com.redhat.ceylon.ide.common.model.CeylonProjects.withLocking$priv$(CeylonProjects.ceylon:89)
	at com.redhat.ceylon.ide.common.model.CeylonProjects.getCeylonProjects(CeylonProjects.ceylon:108)
	at com.redhat.ceylon.ide.common.model.CeylonProjects.fileTreeChanged(CeylonProjects.ceylon:195)
	at com.redhat.ceylon.ide.netbeans.model.CeylonModelManager.notifyChanges$priv$(CeylonModelManager.ceylon:120)
	at com.redhat.ceylon.ide.netbeans.model.CeylonModelManager.fileChanged(CeylonModelManager.ceylon:137)
[catch] at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEventImpl(FCLSupport.java:178)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapperMulti.dispatchAllEventsSync(FCLSupport.java:248)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEvent(FCLSupport.java:137)
	at org.openide.filesystems.FCLSupport.dispatchEvent(FCLSupport.java:112)
	at org.openide.filesystems.FileObject$ED.dispatch(FileObject.java:1435)
	at org.openide.filesystems.FileSystem$EventDispatcher.run(FileSystem.java:795)
	at org.openide.filesystems.EventControl.dispatchEvent(EventControl.java:84)
	at org.openide.filesystems.FileSystem.dispatchEvent(FileSystem.java:554)
	at org.openide.filesystems.FileObject.dispatchEvent(FileObject.java:644)
	at org.openide.filesystems.FileObject.fireFileChangedEvent(FileObject.java:612)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj.fireFileChangedEvent(BaseFileObj.java:717)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObj$1.close(FileObj.java:156)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
	at org.openide.filesystems.FileObject$1.close(FileObject.java:829)
	at org.netbeans.modules.parsing.impl.indexing.IndexerCache.writeLastKnownIndexers(IndexerCache.java:681)
	at org.netbeans.modules.parsing.impl.indexing.IndexerCache.getData(IndexerCache.java:491)
	at org.netbeans.modules.parsing.impl.indexing.IndexerCache.getIndexersMap(IndexerCache.java:134)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$SourceIndexers.<init>(RepositoryUpdater.java:6485)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$SourceIndexers.load(RepositoryUpdater.java:6467)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.getSourceIndexers(RepositoryUpdater.java:2242)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$InitialRootsWork.getDone(RepositoryUpdater.java:5835)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doTheWork(RepositoryUpdater.java:3435)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task._run(RepositoryUpdater.java:6198)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.access$4300(RepositoryUpdater.java:5849)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2$1.run(RepositoryUpdater.java:6114)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:304)
	at org.netbeans.modules.parsing.impl.RunWhenScanFinishedSupport.performScan(RunWhenScanFinishedSupport.java:106)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6110)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6106)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:176)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:360)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:141)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:88)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.run(RepositoryUpdater.java:6106)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
SEVERE [org.openide.util.Exceptions]
com.redhat.ceylon.model.loader.ModelResolutionException: Failed to resolve ceylon.language.empty_
	at com.redhat.ceylon.model.loader.AbstractModelLoader$7.call(AbstractModelLoader.java:2015)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$7.call(AbstractModelLoader.java:1910)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:415)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.embeddingSync(AbstractModelLoader.java:406)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:411)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1910)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1905)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.getDeclaration(AbstractModelLoader.java:5955)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toProducedType(TypeDescriptor.java:318)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toType(TypeDescriptor.java:310)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getProducedType(Metamodel.java:361)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.is(TypeDescriptor.java:1516)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.is(TypeDescriptor.java:270)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.isReified(Metamodel.java:326)
	at com.redhat.ceylon.compiler.java.Util.isReified(Util.java:79)
	at ceylon.language.Iterable$impl.sequence(Iterable.ceylon:289)
	at ceylon.language.Map$impl$Items.sequence(Map.ceylon)
	at com.redhat.ceylon.ide.common.model.CeylonProjects$3.$call$(CeylonProjects.ceylon:110)
	at com.redhat.ceylon.ide.common.model.CeylonProjects.withLocking$priv$(CeylonProjects.ceylon:89)
	at com.redhat.ceylon.ide.common.model.CeylonProjects.getCeylonProjects(CeylonProjects.ceylon:108)
	at com.redhat.ceylon.ide.common.model.CeylonProjects.fileTreeChanged(CeylonProjects.ceylon:195)
	at com.redhat.ceylon.ide.netbeans.model.CeylonModelManager.notifyChanges$priv$(CeylonModelManager.ceylon:120)
	at com.redhat.ceylon.ide.netbeans.model.CeylonModelManager.fileChanged(CeylonModelManager.ceylon:137)
[catch] at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEventImpl(FCLSupport.java:178)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapperMulti.dispatchAllEventsSync(FCLSupport.java:248)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEvent(FCLSupport.java:137)
	at org.openide.filesystems.FCLSupport.dispatchEvent(FCLSupport.java:112)
	at org.openide.filesystems.FileObject$ED.dispatch(FileObject.java:1435)
	at org.openide.filesystems.FileSystem$EventDispatcher.run(FileSystem.java:795)
	at org.openide.filesystems.EventControl.dispatchEvent(EventControl.java:84)
	at org.openide.filesystems.FileSystem.dispatchEvent(FileSystem.java:554)
	at org.openide.filesystems.FileObject.dispatchEvent(FileObject.java:644)
	at org.openide.filesystems.FileObject.fireFileChangedEvent(FileObject.java:612)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj.fireFileChangedEvent(BaseFileObj.java:717)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObj$1.close(FileObj.java:156)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
	at org.openide.filesystems.FileObject$1.close(FileObject.java:829)
	at org.netbeans.modules.parsing.impl.indexing.IndexerCache.writeLastKnownIndexers(IndexerCache.java:681)
	at org.netbeans.modules.parsing.impl.indexing.IndexerCache.getData(IndexerCache.java:491)
	at org.netbeans.modules.parsing.impl.indexing.IndexerCache.access$400(IndexerCache.java:90)
	at org.netbeans.modules.parsing.impl.indexing.IndexerCache$4.run(IndexerCache.java:518)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
SEVERE [null]: Last record repeated again.
INFO [org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater]: Resolving dependencies took: 4.965 ms
INFO [org.netbeans.core.ui.focus]: External Changes Refresh on focus gain disabled
SEVERE [org.openide.util.Exceptions]
com.redhat.ceylon.model.loader.ModelResolutionException: Failed to resolve ceylon.language.empty_
	at com.redhat.ceylon.model.loader.AbstractModelLoader$7.call(AbstractModelLoader.java:2015)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$7.call(AbstractModelLoader.java:1910)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:415)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.embeddingSync(AbstractModelLoader.java:406)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:411)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1910)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1905)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.getDeclaration(AbstractModelLoader.java:5955)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toProducedType(TypeDescriptor.java:318)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toType(TypeDescriptor.java:310)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getProducedType(Metamodel.java:361)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.is(TypeDescriptor.java:1516)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.is(TypeDescriptor.java:270)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.isReified(Metamodel.java:326)
	at com.redhat.ceylon.compiler.java.Util.isReified(Util.java:79)
	at ceylon.language.Iterable$impl.sequence(Iterable.ceylon:289)
	at ceylon.language.Map$impl$Items.sequence(Map.ceylon)
	at com.redhat.ceylon.ide.common.model.CeylonProjects$3.$call$(CeylonProjects.ceylon:110)
	at com.redhat.ceylon.ide.common.model.CeylonProjects.withLocking$priv$(CeylonProjects.ceylon:89)
	at com.redhat.ceylon.ide.common.model.CeylonProjects.getCeylonProjects(CeylonProjects.ceylon:108)
	at com.redhat.ceylon.ide.common.model.CeylonProjects.fileTreeChanged(CeylonProjects.ceylon:195)
	at com.redhat.ceylon.ide.netbeans.model.CeylonModelManager.notifyChanges$priv$(CeylonModelManager.ceylon:120)
	at com.redhat.ceylon.ide.netbeans.model.CeylonModelManager.fileChanged(CeylonModelManager.ceylon:137)
[catch] at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEventImpl(FCLSupport.java:178)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapperMulti.dispatchAllEventsSync(FCLSupport.java:248)
	at org.openide.filesystems.FCLSupport$DispatchEventWrapper.dispatchEvent(FCLSupport.java:137)
	at org.openide.filesystems.FCLSupport.dispatchEvent(FCLSupport.java:112)
	at org.openide.filesystems.FileObject$ED.dispatch(FileObject.java:1435)
	at org.openide.filesystems.FileSystem$EventDispatcher.run(FileSystem.java:795)
	at org.openide.filesystems.EventControl.dispatchEvent(EventControl.java:84)
	at org.openide.filesystems.FileSystem.dispatchEvent(FileSystem.java:554)
	at org.openide.filesystems.FileObject.dispatchEvent(FileObject.java:644)
	at org.openide.filesystems.FileObject.fireFileChangedEvent(FileObject.java:612)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.BaseFileObj.fireFileChangedEvent(BaseFileObj.java:717)
	at org.netbeans.modules.masterfs.filebasedfs.fileobjects.FileObj$1.close(FileObj.java:156)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
	at org.netbeans.modules.parsing.impl.indexing.ArchiveTimeStamps$Saver.run(ArchiveTimeStamps.java:226)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

```

**Comment by bjansen** [comment]
Well of course, the fix hasn't been published in nightly builds yet :)

**Comment by bjansen** [comment]
Could you tell NetBeans to check for updates and see if the build that was published a few minutes ago fixed the problem please?

**Comment by Chris2011** [comment]
Ok, didn't notice that. I will check it later. thx.
